# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa82b1b138468e2a6e5f215bbf17c0db6fd3c37ba79e483f91aa3d62b04d15806b0729f1501dd00e5b819cad294b3773c56245d2c9db5e874aa0f7a3817a36ab

test:
  secret_key_base: 788680ad917c5a87d11eafde3a795d0c9de5e838f8bd2a3b682258dbfd8a228b7d3508cc3e0e594b7a5d1e174320f6a4f66016ba91e9f49ce873baf582801d39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
